Age
michael120288/21806-MLH pull request #2
Opened 2021-04-04 22:42 UTC by IliaKopylov

Create agePositive.js, add to selectors, testData, expected. Change wdioConfig included runs.

2021-04-05 20:24 UTC, michael120288 commented on test/extended/agePositive.js
> +import sel from '../../data/selectors'; // импорт в переменную 'sel' константы из файла selectors.js
Delete comments or at least do it on english

2021-04-05 20:25 UTC, michael120288 commented on test/extended/agePositive.js
> +//const sel = require('../data/selectors'); старый вариант
delete

2021-04-05 20:46 UTC, michael120288 commented on test/extended/agePositive.js
> +            //expect(submitButton).toEqual(true); //compare {title} (actual) and "MLH trial" (expected)
you don't need to leave the comments that we don't use

2021-04-05 20:47 UTC, michael120288 commented on test/extended/agePositive.js
> +});
add empty line in the end)

2021-04-05 20:48 UTC, michael120288 commented on test/extended/agePositive.js
> +            //expect(submitButton).toEqual(true); //compare {title} (actual) and "MLH trial" (expected)
line that we don't use

2021-04-05 20:49 UTC, michael120288 commented on test/extended/ageNegative.js
> +
empty lines that need to delete

2021-04-05 20:50 UTC, michael120288 commented on data/expected.json
> +}
add an empty line in the end)

2021-04-05 20:51 UTC, michael120288 commented on data/selectors.js
> +
delete line

2021-04-06 00:08 UTC, michael120288 requested changes
look at my comments

2021-04-06 00:22 UTC, michael120288 requested changes
again

2021-04-06 00:28 UTC, IliaKopylov reviewed
I fixed all

2021-04-06 00:46 UTC, michael120288 requested changes
again

2021-04-06 00:46 UTC, michael120288 commented on test/extended/ageNegative.js
> +*/
Delete

2021-04-06 00:46 UTC, michael120288 commented on test/extended/ageNegative.js
> +//const sel = require('../data/selectors'); старый вариант
delete

2021-04-06 00:46 UTC, michael120288 commented on helpers/methods.js
> +//export default all;
delete

2021-04-06 00:46 UTC, michael120288 commented on test/extended/ageNegative.js
> +// import inputFieldClear from '../../helpers/methods';
Delete

2021-04-06 00:52 UTC, michael120288 commented
Again

2021-04-06 00:52 UTC, closed without merging